### ISSUE TITLE
Android - avutil not found

### ISSUE THREAD

**Issue by allbabel** [wang-bin/QtAV#420] opened 2015-04-27 11:41 UTC
I am trying to build QtAV for Android.  I have built ffmpeg using ffmpeg-android project on github and copied the arm-v7a libraries and headers to my Qt installation directory for Android.  
I have configured Qt Creator to build for Android but I get this message:

error: avutil is required, but compiler can not find it

I have set static_ffmpeg in .qmake.conf so I am lost why qmake can't find libavutil.a which I have copied to ~/Qt/5.4/android_armv7/lib

**Comment by wang-bin** [comment] 2015-04-27 12:06
show me config.log in build dir.
you can just use QtAV/script/build_ffmpeg.sh to build ffmpeg, copy it to ffmpeg dir, create config-android.sh with content `NDK_ROOT=some_path`, then run `./build_ffmpeg.sh android arm`
To build static libs, comment out `: ${LIB_OPT:="--enable-shared"}` in build_ffmpeg.sh

**Comment by allbabel** [comment] 2015-04-27 13:16
Here is the FFMPEG config.log https://www.dropbox.com/s/kg706libe9e8uug/config.log?dl=0
I have already tried building with the QtAV scripts and it failed a couple of times - I will try again and let you know.

**Comment by wang-bin** [comment] 2015-04-27 13:29
I mean confing.log in QtAV build dir

**Comment by allbabel** [comment] 2015-04-27 14:40
https://www.dropbox.com/s/kg706libe9e8uug/config.log?dl=0

**Comment by wang-bin** [comment] 2015-04-27 15:10
your log is ok. i don't see `avutil not found`

**Comment by allbabel** [comment] 2015-04-28 09:16
For that reason I am confused - when I run qmake from QtCreator it shows that error message.

**Comment by pkoretic** [comment] 2015-05-05 20:09
@allbabel how do you run that qmake? Using qtcreator build only?
Can you paste build output (to pastebin)
also you can see in project details in qt creator what environment variables are set

**Comment by nechosa** [comment] 2015-05-20 13:53
I have the same issue. My QtCreator(Qt Creator 3.3.0 (opensource)) log
<b>
Project MESSAGE: BUILD_DIR=C:/build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_4_0-Debug
Project MESSAGE: MAKEFILE_GENERATOR=UNIX
Project MESSAGE: target arch: 
Project MESSAGE: target arch features: 
Project MESSAGE: To disable config tests, you can use 1 of the following methods
Project MESSAGE: 1. create '.qmake.conf' in the root source dir, add 'CONFIG += no_config_tests'(Qt5)
Project MESSAGE: 2. pass 'CONFIG += no_config_tests' or '-config no_config_tests' to qmake
Project MESSAGE: 3. add 'CONFIG += no_config_tests' in C:/QtAV-1.6/user.conf
Project MESSAGE: To manually set a config test result to true, disable config tests and enable config_name like above
Checking for avutil... no
Project ERROR: avutil is required, but compiler can not find it
</b>
I copied /depends/FFmpeg/android/ffmpeg-2.2-android-armv7a(lib,include) in C:\Qt\Qt5.4.0\5.4\android_armv7(lib,include)

I set path enviroment variable, but it not working! Compiler can not find avutil. Why not find avutil?
Can you tell me what am i doing wrong?
Thank you

**Comment by wang-bin** [comment] 2015-05-20 15:20
@nechosa show me your config.log in build dir

**Comment by nechosa** [comment] 2015-05-21 06:35
my log https://yadi.sk/i/F6bQEJY9gmom8

**Comment by wang-bin** [comment] 2015-05-21 08:28
@nechosa try a new ffmpeg release http://sourceforge.net/projects/qtav/files/depends/FFmpeg/android/ffmpeg-2.6.2-android-armv7.tar.xz/download

**Comment by nechosa** [comment] 2015-05-21 09:04
Now everything is fine, but there is an error
<b>
Makefile.libQmlAV:427: recipe for target '..\bin\QtAV\Video.qml' failed
process_begin: CreateProcess(NULL, cp -f C:\QtAV-master\qml\Video.qml C:\build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_4_0-Release\bin\QtAV, ...) failed.
make (e=2): Не удается найти указанный файл.

mingw32-make[1]: [..\bin\QtAV\Video.qml] Error 2 (ignored)
</b>

**Comment by wang-bin** [comment] 2015-05-21 13:46
@nechosa I think there is no `cp` command on windows

**Comment by nechosa** [comment] 2015-05-21 21:59
Thank you for your help.  I run build apk-file in API 15, API 17.
My emulator write "Unfortunaly, QML_Player has stopped",
Can you tell me what am i doing wrong? Can I run build application in my phone?

And Why?
<b>
Warning: QML import could not be resolved in any of the import paths: QtAV
Warning: QML import could not be resolved in any of the import paths: QtAV
</b>

**Comment by nechosa** [comment] 2015-05-21 22:07
my log https://yadi.sk/i/0y6Pl3_kgo2X7

**Comment by wang-bin** [comment] 2015-05-22 04:42
I think you have to use Qt5.3 or Qt5.5 but not Qt5.4. Qt5.4 can not correctly add qml modules in apk. I don't know why. You can compare the content of your apk with my apk

**Comment by wang-bin** [comment] 2015-05-22 04:47
btw, you have to run `qtav_build_dir/sdk_install.sh` after qtav is built. Then create apk again. Otherwise libQt5AV.so will not be added to apk

**Comment by nechosa** [comment] 2015-05-24 09:55
ls -l lib_linux_arm/
<b>
-rw-r--r-- 1 ilua ilua  251348 мая   24 12:49 libcommon.a
-rw-r--r-- 1 ilua ilua    1746 мая   24 12:49 libcommon.prl
-rwxr-xr-x 1 ilua ilua  250456 мая   24 12:49 libQmlAV.so
-rw-r--r-- 1 ilua ilua    1188 мая   24 12:49 libQtAV.prl
lrwxrwxrwx 1 ilua ilua      16 мая   24 12:49 libQtAV.so -> libQtAV.so.1.6.0
lrwxrwxrwx 1 ilua ilua      16 мая   24 12:49 libQtAV.so.1 -> libQtAV.so.1.6.0
lrwxrwxrwx 1 ilua ilua      16 мая   24 12:49 libQtAV.so.1.6 -> libQtAV.so.1.6.0
-rwxr-xr-x 1 ilua ilua 1071724 мая   24 12:49 libQtAV.so.1.6.0
-rw-r--r-- 1 ilua ilua    1196 мая   24 12:49 libQtAVWidgets.prl
lrwxrwxrwx 1 ilua ilua      23 мая   24 12:49 libQtAVWidgets.so -> libQtAVWidgets.so.1.6.0
lrwxrwxrwx 1 ilua ilua      23 мая   24 12:49 libQtAVWidgets.so.1 -> libQtAVWidgets.so.1.6.0
lrwxrwxrwx 1 ilua ilua      23 мая   24 12:49 libQtAVWidgets.so.1.6 -> libQtAVWidgets.so.1.6.0
-rwxr-xr-x 1 ilua ilua  127040 мая   24 12:49 libQtAVWidgets.so.1.6.0
</b>
I run sdk_install.sh. It cannot find libcommon.so. I change skript libcommon.so to   libcommon.a.
But Error:
<b>
your application encountered a fatal error and can no longer work
</b>

**Comment by nechosa** [comment] 2015-05-24 09:56
I buil in Qt5.4.1, 5.3.2, 5.2.1. Same error!

**Comment by wang-bin** [comment] 2015-05-24 15:40
@nechosa Libcommon.so is not required. I will update the script. You have to use qt5.3 or 5.5 because 5.4 can not pack qml modules correctly

**Comment by nechosa** [comment] 2015-05-24 20:46
My log Qt 5.3.0. Same error! Can you tell me what am i doing wrong?
<b>
Запуск внешнего процесса.D/dalvikvm(24481): Zygote::ForkAndSpecialize : 0
D/dalvikvm(24481): zygote get new systemTid : 24481
D/dalvikvm(24481): Late-enabling CheckJNI
D/jdwp    (24481): prepping for JDWP over ADB
D/jdwp    (24481): ADB transport startup
D/dalvikvm(24481): Elevating priority from 0 to -8
D/jdwp    (24481): JDWP: thread running
D/jdwp    (24481): acceptConnection
D/jdwp    (24481): trying to receive file descriptor from ADB
D/dalvikvm(24481): zygote get thread init done
W/asset   (24481): AssetManager-->addDefaultAssets CIP path not exsit!
D/dalvikvm(24481): Trying to load lib /data/data/org.qtav.qmlplayer/lib/libgnustl_shared.so 0x42499490
D/dalvikvm(24481): Added shared lib /data/data/org.qtav.qmlplayer/lib/libgnustl_shared.so 0x42499490
D/dalvikvm(24481): No JNI_OnLoad found in /data/data/org.qtav.qmlplayer/lib/libgnustl_shared.so 0x42499490, skipping init
D/dalvikvm(24481): Trying to load lib /data/data/org.qtav.qmlplayer/lib/libavutil.so 0x42499490
D/dalvikvm(24481): Added shared lib /data/data/org.qtav.qmlplayer/lib/libavutil.so 0x42499490
D/dalvikvm(24481): No JNI_OnLoad found in /data/data/org.qtav.qmlplayer/lib/libavutil.so 0x42499490, skipping init
D/dalvikvm(24481): Trying to load lib /data/data/org.qtav.qmlplayer/lib/libswresample.so 0x42499490
D/dalvikvm(24481): Added shared lib /data/data/org.qtav.qmlplayer/lib/libswresample.so 0x42499490
D/dalvikvm(24481): No JNI_OnLoad found in /data/data/org.qtav.qmlplayer/lib/libswresample.so 0x42499490, skipping init
D/dalvikvm(24481): Trying to load lib /data/data/org.qtav.qmlplayer/lib/libswscale.so 0x42499490
D/dalvikvm(24481): Added shared lib /data/data/org.qtav.qmlplayer/lib/libswscale.so 0x42499490
D/dalvikvm(24481): No JNI_OnLoad found in /data/data/org.qtav.qmlplayer/lib/libswscale.so 0x42499490, skipping init
D/dalvikvm(24481): Trying to load lib /data/data/org.qtav.qmlplayer/lib/libavcodec.so 0x42499490
E/linker  (24481): soinfo_relocate(linker.cpp:987): cannot locate symbol "log2f" referenced by "libavcodec.so"...
E/dalvikvm(24481): dlopen("/data/data/org.qtav.qmlplayer/lib/libavcodec.so") failed: Cannot load library: soinfo_relocate(linker.cpp:987): cannot locate symbol "log2f" referenced by "libavcodec.so"...
W/System.err(24481): java.lang.reflect.InvocationTargetException
W/System.err(24481): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(24481): 	at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err(24481): 	at org.qtproject.qt5.android.bindings.QtActivity.loadApplication(QtActivity.java:242)
W/System.err(24481): 	at org.qtproject.qt5.android.bindings.QtActivity.startApp(QtActivity.java:643)
W/System.err(24481): 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:872)
W/System.err(24481): 	at org.qtav.qmlplayer.QMLPlayerActivity.onCreate(QMLPlayerActivity.java:24)
W/System.err(24481): 	at android.app.Activity.performCreate(Activity.java:5122)
W/System.err(24481): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
W/System.err(24481): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
W/System.err(24481): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
W/System.err(24481): 	at android.app.ActivityThread.access$600(ActivityThread.java:162)
W/System.err(24481): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
W/System.err(24481): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(24481): 	at android.os.Looper.loop(Looper.java:194)
W/System.err(24481): 	at android.app.ActivityThread.main(ActivityThread.java:5392)
W/System.err(24481): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(24481): 	at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err(24481): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
W/System.err(24481): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
W/System.err(24481): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err(24481): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:987): cannot locate symbol "log2f" referenced by "libavcodec.so"...
W/System.err(24481): 	at java.lang.Runtime.load(Runtime.java:341)
W/System.err(24481): 	at java.lang.System.load(System.java:500)
W/System.err(24481): 	at org.qtproject.qt5.android.QtNative.loadQtLibraries(QtNative.java:132)
W/System.err(24481): 	at org.qtproject.qt5.android.QtActivityDelegate.loadApplication(QtActivityDelegate.java:410)
W/System.err(24481): 	... 20 more
I/QMLPlayerActivity(24481): Action: null
I/QMLPlayerActivity(24481): Data: null
V/PhoneWindow(24481): DecorView setVisiblity: visibility = 4
V/PhoneWindow(24481): DecorView setVisiblity: visibility = 0
D/libEGL  (24481): loaded /system/lib/egl/libEGL_mali.so
D/libEGL  (24481): loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL  (24481): loaded /system/lib/egl/libGLESv2_mali.so
D/OpenGLRenderer(24481): Enabling debug mode 0
I/SurfaceTextureClient(24481): [STC::queueBuffer] (this:0x51691178) fps:8.88, dur:1013.25, max:876.92, min:6.74
I/SurfaceTextureClient(24481): [STC::queueBuffer] (this:0x51691178) fps:0.19, dur:25708.38, max:25632.29, min:18.11
I/SurfaceTextureClient(24481): [STC::queueBuffer] this:0x51691178, api:1, last queue time elapsed:25632.29
V/Provider/Settings(24481): invalidate [system]: current 289 != cached 0
D/ActivityThread(24481): installProvider: context=android.app.ContextImpl@4249d4e0holder=android.app.IActivityManager$ContentProviderHolder@425b8be8noisy=truenoReleaseNeeded=truestable=true
V/Provider/Settings(24481): from db cache, name = sound_effects_enabled , value = 1
D/OpenGLRenderer(24481): Flushing caches (mode 0)
D/OpenGLRenderer(24481): Flushing caches (mode 0)
D/OpenGLRenderer(24481): Flushing caches (mode 1)
D/OpenGLRenderer(24481): Flushing caches (mode 0)


«org.qtav.qmlplayer» завершился крахом.
</b>

**Comment by wang-bin** [comment] 2015-05-25 02:50
@nechosa  can not load libavcodec.so. what's your android version? You can try to build ffmpeg with gcc 4.6 instead of 4.8.

**Comment by nechosa** [comment] 2015-05-25 12:04
API 17 (Android 4.2.2). You mean Android GCC(arm-4.8)?
ffmpeg-2.6.2-android-armv7.tar.xz - build in 4.6 or 4.8?

**Comment by wang-bin** [comment] 2015-05-25 12:11
try gcc 4.6

It's 4.8. see QtAV/scripts/build_ffmpeg.sh. you can change 4.8 to 4.6 in this script and build ffmpeg.

**Comment by nechosa** [comment] 2015-05-25 12:31
cannot locate symbol "log2f" referenced by "libavcodec.so"

**Comment by nechosa** [comment] 2015-05-25 12:32
which Android GCC(arm-) you used?

**Comment by wang-bin** [comment] 2015-05-25 13:00
@nechosa 4.8

**Comment by nechosa** [comment] 2015-05-26 06:14
I've built 4.8 and run the application in the Android API 17. Everything is now okay. My mistake. Can QMLPlayer play RTSP stream in Android?

**Comment by wang-bin** [comment] 2015-05-26 06:19
@nechosa yes it can

**Comment by wang-bin** [comment] 2015-06-16 09:48
avutil not found on for android on windows should be fixed in 54074da

**Closed** 2015-06-16 09:50 UTC

**Comment by sevdeveloper** [comment] 2015-09-12 15:43
Hi! I have the same issue: **avutil is required, but compiler can not find it**

I copied include/libs from *ffmpeg-2.8.0-android-armv7.tar.xz* to *D:\Qt\5.5\android_armv7* and from *ffmpeg-2.7.1-mingw+msvc-x86+x64.7z* to *D:\Qt\5.5\mingw492_32*

I try to compile QtAV 1.8.0 project on Win7(x32), Qt Creator 3.5.0 (opensource) for android armeabi v7a, GCC 4.9, Qt 5.5.0 and have this error.
Build for windows desktop MinGW is passing ok.

Build log:
**18:20:50: Запускается: «D:\Qt\5.5\android_armv7\bin\qmake.exe» D:\Projects\qtav\QtAV.pro -r -spec android-g++
‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
Project MESSAGE: BUILD_DIR=D:/Projects/build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_5_0-Release
Project MESSAGE: MAKEFILE_GENERATOR=UNIX
Project MESSAGE: target arch: 
Project MESSAGE: target arch features: 
Project MESSAGE: To disable config tests, you can use 1 of the following methods
Project MESSAGE: 1. create '.qmake.conf' in the root source dir, add 'CONFIG += no_config_tests'(Qt5)
Project MESSAGE: 2. pass 'CONFIG += no_config_tests' or '-config no_config_tests' to qmake
Project MESSAGE: 3. add 'CONFIG += no_config_tests' in D:/Projects/qtav/user.conf
Project MESSAGE: To manually set a config test result to true, disable config tests and enable config_name like above
Checking for avutil... no
Project ERROR: avutil is required, but compiler can not find it
18:20:52: Процесс «D:\Qt\5.5\android_armv7\bin\qmake.exe» завершился с кодом 3.**

config.log :
**executing config test avutil
cd D:\Projects\build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_5_0-Release\config.tests\avutil && mingw32-make distclean
"mingw32-make" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
cd D:\Projects\build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_5_0-Release\config.tests\avutil && D:\Qt\5.5\android_armv7\bin\qmake.exe -spec D:/Qt/5.5/android_armv7/mkspecs/android-g++ "CONFIG -= qt debug_and_release app_bundle lib_bundle" D:/Projects/qtav/config.tests/avutil
cd D:\Projects\build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_5_0-Release\config.tests\avutil && mingw32-make
"mingw32-make" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
test avutil FAILED**

I also tried to  use previous versions of ffmpeg, e.g.: 2.7.1, 2.7.0, 2.6.2, tried to add paths in CPATH and LIBRARY_PATH wich point to unpacked files, but it did not help.

How can I fix it?
Thanks.

**Comment by wang-bin** [comment] 2015-09-12 17:40
@sevdeveloper  https://github.com/wang-bin/QtAV/wiki/Build-QtAV#user-content-recommended-put-ffmpeg-headers-and-libs-into-qt-directories

copy ffmpeg's include and lib to qt's include and lib dir. it works for every environment

**Comment by sevdeveloper** [comment] 2015-09-12 18:14
Yes, I do this, for windows desktop I use files from this http://sourceforge.net/projects/qtav/files/depends/FFmpeg/windows/ffmpeg-2.7.1-mingw%2Bmsvc-x86%2Bx64.7z/download package and for android this http://sourceforge.net/projects/qtav/files/depends/FFmpeg/android/ffmpeg-2.8.0-android-armv7.tar.xz/download package. Desktop project compiled fine, but android buld can not find avutil...

**Comment by wang-bin** [comment] 2015-09-12 19:29
@sevdeveloper show me the config.log in build dir

**Comment by sevdeveloper** [comment] 2015-09-12 20:11
config.log in adroid project:
**executing config test avutil
+ cd D:\Projects\build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_5_0-Release\config.tests\avutil && mingw32-make distclean
"mingw32-make" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
+ cd D:\Projects\build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_5_0-Release\config.tests\avutil && D:\Qt\5.5\android_armv7\bin\qmake.exe -spec D:/Qt/5.5/android_armv7/mkspecs/android-g++ "CONFIG -= qt debug_and_release app_bundle lib_bundle" D:/Projects/qtav/config.tests/avutil
+ cd D:\Projects\build-QtAV-Android_armeabi_v7a_GCC_4_9_Qt_5_5_0-Release\config.tests\avutil && mingw32-make
"mingw32-make" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
test avutil FAILED**

config.log in desktop project (passing): http://pastebin.com/CaMfHmuX

I noticed that the log for android missing two lines starting with "g++ ..."

**Comment by wang-bin** [comment] 2015-09-12 20:16
what's the `make` program for your android toolchain? `mingw32-make.exe` or something else?

**Comment by sevdeveloper** [comment] 2015-09-12 20:26
Yes, it is
D:\Qt\Tools\mingw492_32\bin\mingw32-make.exe

**Comment by wang-bin** [comment] 2015-09-13 01:43
no, it's desktop app toolchain, not for android. do you have android toolchain? how about building a simple android app?

**Comment by sevdeveloper** [comment] 2015-09-13 10:28
I build sample qt project "collidingmice" and see mingw32-make.exe in build log: http://pastebin.com/usUn03Ky
Apk created and works on emulator

**Comment by wang-bin** [comment] 2015-09-13 15:55
I have no idea. you can try to create `.qmake.cache` in build dir and add some lines `CONFIG+=config_xxx config_xxx_done`, replace `xxx` with `avutil avcodec avformat avfilter swscale swresample`

**Comment by sevdeveloper** [comment] 2015-09-15 18:32
Ok. I try this, but has other error http://pastebin.com/upfpBZHb
I decide to try another OS and had successful build on CentOS 7 64, and I think this is solution for me. However, thank you for answers, it is valuable!
