### ISSUE TITLE
segmentation fault - qmplayer

### ISSUE THREAD

**Issue by saqebakhter** [wang-bin/QtAV#374] opened 2015-02-16 06:33 UTC
I keep getting a segmentation fault when i switch the video being played back : the log file shows the first file being loaded, and then the 2nd - and then the stack trace for the segfault. 

Debugging starts
&"warning: GDB: Failed to set controlling terminal: Inappropriate ioctl for device\n"
QML debugging is enabled. Only use this in a safe environment.
unknow option:  "-qmljsdebugger=port:56677,block"
"Options for QtAV players
common options
  -h [--help]                      print this
  -gl value                        OpenGL backend for Qt>=5.4(windows). can be 'auto', 'desktop', 'angle' and 'software' (default: auto)
  -x value                          (default: 0)
  -fullscreen                      fullscreen
  -height value                    height of player (default: 450)
  -deocder value                   use a given decoder (default: FFmpeg)
  -language value                  language on UI. can be 'system', 'none' and locale name e.g. zh_CN (default: system)
  -width value                     width of player (default: 800)
  -y value                         y (default: 0)
  -vd [--decoders] value           decoder name list in priority order seperated by ';' (default: cuda;vaapi;vda;dxva;cedarv;ffmpeg)
  -f [--file] value                file or url to play
QMLPlayer options
  -scale value                     scale of graphics context. 0: auto (default: 1)"
QML Debugger: Waiting for connection on port 56677...
("/home/sakhter/source/build-QtAV-Desktop_Qt_5_4_0_GCC_64bit-Debug/bin", "/home/sakhter/Qt/5.4/gcc_64/qml")
>>>>>>>>devicePixelRatio: 1.000000
dpi phy:  96.0252 , logical:  96 , dpr:  1 ; vis rect: QRect(0,0 1440x900)
capi::version: 0.0.2
qml: init>>>>>screen density logical: 3.7795275590551185 pixel: 3.780520082048567
ScreenSaver::retrieveState
ScreenSaver::retrieveState timeout: 0, interval: 600, preferBlanking:1, allowExposures:1
ScreenSaver::enable 0, ret 1 timeout origin: 0
Succeed to enable screen saver (0)
"QtAV 1.5.0(Feb 15 2015, 21:57:01)
A media playing library base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Copyright (C) 2012-2015 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Shanghai University->S3 Graphics->Deepin, Shanghai, China
Donate: http://www.qtav.org#donate
Source: https://github.com/wang-bin/QtAV
Home page: http://www.qtav.org"
"Build with libavutil-54.7.100"
"Build with libavcodec-56.1.100"
"Build with libavformat-56.4.101"
"Build with libavfilter-5.1.100"
"Build with libavdevice-56.0.100"
"Build with libavresample-2.1.0"
"Build with libswresample-1.1.100"
"Build with libswscale-3.0.100"
Loading  QVariant(QString, "/run/user/1000/gvfs/smb-share:server=192.168.10.56,share=2tb2/Shares/TVShows/2 Broke Girls/Season 4/2 Broke Girls - S04E04 - And the Old Bike Yarn WEBDL-1080p.mkv")  ...
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0x7fffa4004400', url:'/run/user/1000/gvfs/smb-share:server=192.168.10.56,share=2tb2/Shares/TVShows/2 Broke Girls/Season 4/2 Broke Girls - S04E04 - And the Old Bike Yarn WEBDL-1080p.mkv'..."
"avformat_open_input: url:'/run/user/1000/gvfs/smb-share:server=192.168.10.56,share=2tb2/Shares/TVShows/2 Broke Girls/Season 4/2 Broke Girls - S04E04 - And the Old Bike Yarn WEBDL-1080p.mkv' ret:0"
"[FFmpeg:h264] Increasing reorder buffer to 1"
"has audio"
"avcodec_register_all"
"trying audio output 'OpenAL'"
"audio output found."
"OpenAL audioFormatToAL error: "
"OpenAL audio format: 0x1103 ch:2, sample format: s16"
"ao audio format is changed. reopen ao"
"OpenAL audioFormatToAL error: "
"OpenAL audio format: 0x1103 ch:2, sample format: s16"
"notify_interval: 500"
"stream: 1, duration=-9223372036854775808 (-9223372036854775808 ms), time_base=0.001000"
"codec: ac3(ATSC A/52A (AC-3))"
"stream: 0, duration=-9223372036854775808 (-9223372036854775808 ms), time_base=0.001000"
"codec: h264(H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)"
"OpenAL devices available: 1"
"device 0: ES1371 / Creative Labs CT2518 [AudioPCI-97] (AudioPCI 64V/128 / Creative Sound Blaster CT4810) Analog Stereo"
"AudioOutputOpenAL Opening default device: OpenAL Soft"
"AudioOutputOpenAL creating context..."
"OpenAL 1.1 ALSOFT 1.15.1 vendor: OpenAL Community; renderer: OpenAL Soft"
"device: 0x12a9430, context: 0x126f600"
"OpenAL audio format: 0x1103 ch:2, sample format: s16"
"AudioOutputOpenAL open ok..."
"swr speed=1.00"
"out: {cl: 3, fmt: s16, freq: 48000}"
"in {cl: 1551, fmt: fltp, freq: 48000}"
"new audio thread"
"demux thread setAudioThread"
"output not changed: 0x817ef0"
"set AVThread output"
"**********trying video decoder: FFmpeg..."
"**************Video decoder found"
"setCapture 0x816ac0"
"auto select clock: audio > external"
"Using AudioClock"
"Clock initial value: 0.000000"
"Starting audio thread..."
"Starting video thread..."
"demux thread start running...2 avthreads"
"get av queue a/v thread = 0x128ada0 0x817d30"
"AVClock started!!!!!!!!"
"AudioOutputOpenAL: !AL_PLAYING alSourcePlay"
"no frame could be decompressed: Error number 859 occurred"
invalid video frame from decoder
"setInSize => calculating aspect ratio from converted input data(1.780669)"
"pixel format changed:  => yuv420p"
"glGetUniformLocation("u_Texture0") = 1"
"glGetUniformLocation("u_Texture1") = 2"
"glGetUniformLocation("u_Texture2") = 3"
"glGetUniformLocation("u_MVP_matrix") = 0"
"glGetUniformLocation("u_colorMatrix") = 5"
"glGetUniformLocation("u_bpp") = -1"
"glGetUniformLocation("u_opacity") = 4"
"plane linesize 0: padded = 1920, effective = 1916"
"plane width 1920: effective = 1916"
"planeHeight 0 = 1076"
"plane linesize 1: padded = 960, effective = 958"
"plane width 960: effective = 958"
"planeHeight 1 = 538"
"plane linesize 2: padded = 960, effective = 958"
"plane width 960: effective = 958"
"planeHeight 2 = 538"
"effective_tex_width_ratio=0.997917"
"///////////bpp 2"
"texture width: 1920 - 1916 = pad: 4. bpp(gl): 1"
"texture width: 960 - 958 = pad: 2. bpp(gl): 1"
"texture width: 960 - 958 = pad: 2. bpp(gl): 1"
"delete 0 textures"
"init textures..."
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0x7fffc8021c60', url:'/run/user/1000/gvfs/smb-share:server=192.168.10.56,share=2tb2/Shares/TVShows/2 Broke Girls/Season 4/2 Broke Girls - S04E04 - And the Old Bike Yarn WEBDL-1080p.mkv'..."
"avformat_open_input: url:'/run/user/1000/gvfs/smb-share:server=192.168.10.56,share=2tb2/Shares/TVShows/2 Broke Girls/Season 4/2 Broke Girls - S04E04 - And the Old Bike Yarn WEBDL-1080p.mkv' ret:0"
"[FFmpeg:h264] Increasing reorder buffer to 1"
"timer is not valid, start it"
"avcodec option: skip_frame=>0"
"no frame could be decompressed: Error number 224274 occurred"
"got frame at 891.099000s, diff=18"
"setInSize => calculating aspect ratio from converted input data(1.780669)"
"pixel format changed:  => yuv420p"
"plane linesize 0: padded = 1920, effective = 1916"
"plane width 1920: effective = 1916"
"planeHeight 0 = 1076"
"plane linesize 1: padded = 960, effective = 958"
"plane width 960: effective = 958"
"planeHeight 1 = 538"
"plane linesize 2: padded = 960, effective = 958"
"plane width 960: effective = 958"
"planeHeight 2 = 538"
"effective_tex_width_ratio=0.997917"
"///////////bpp 2"
"texture width: 1920 - 1916 = pad: 4. bpp(gl): 1"
"texture width: 960 - 958 = pad: 2. bpp(gl): 1"
"texture width: 960 - 958 = pad: 2. bpp(gl): 1"
"delete 0 textures"
"init textures..."
"avcodec option: skip_frame=>0"
"avcodec option: skip_frame=>8"
"no frame could be decompressed: Error number 26744 occurred"
"no frame could be decompressed: Error number 24811 occurred"
"no frame could be decompressed: Error number 22192 occurred"
"no frame could be decompressed: Error number 21322 occurred"
"no frame could be decompressed: Error number 19226 occurred"
"no frame could be decompressed: Error number 20626 occurred"
"no frame could be decompressed: Error number 20218 occurred"
"no frame could be decompressed: Error number 20451 occurred"
"no frame could be decompressed: Error number 21310 occurred"
"no frame could be decompressed: Error number 21399 occurred"
"no frame could be decompressed: Error number 18359 occurred"
"no frame could be decompressed: Error number 16652 occurred"
"avcodec option: skip_frame=>0"
"got frame at 948.407000s, diff=5"
"timer: 3, current thread: 0x621220, player thread: 0x621220"
"stopping demuxer thread..."
"stopping audio thread......."
"Audio thread stops running..."
"stopping video thread......."
"setInSize => calculating aspect ratio from converted input data(1.000000)"
"pixel format changed: yuv420p => "
"Video thread stops running..."
"all avthread finished. try to exit demux thread<<<<<<"
"Demux thread stops running...."
"all audio/video threads  stopped..."
"closing d->format_ctx"
"demuxer thread emit finished."
"avplayer emit stopped()"
"setInSize => calculating aspect ratio from converted input data(1.000000)"
"pixel format changed: yuv420p => "
Loading  QVariant(QString, "/run/user/1000/gvfs/smb-share:server=192.168.10.56,share=2tb2/Shares/TVShows/2 Broke Girls/Season 4/2 Broke Girls - S04E02 - And the DJ Face WEBDL-1080p.mkv")  ...
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0x7fffa40d00c0', url:'/run/user/1000/gvfs/smb-share:server=192.168.10.56,share=2tb2/Shares/TVShows/2 Broke Girls/Season 4/2 Broke Girls - S04E02 - And the DJ Face WEBDL-1080p.mkv'..."
"closing d->format_ctx"
"avformat_open_input: url:'/run/user/1000/gvfs/smb-share:server=192.168.10.56,share=2tb2/Shares/TVShows/2 Broke Girls/Season 4/2 Broke Girls - S04E02 - And the DJ Face WEBDL-1080p.mkv' ret:0"
"[FFmpeg:h264] Increasing reorder buffer to 1"

stack trace:

0	QtAV::AVPlayer::Private::initCommonStatistics	AVPlayerPrivate.cpp	209	0x7fffda273d27	
1	QtAV::AVPlayer::Private::initAudioStatistics	AVPlayerPrivate.cpp	235	0x7fffda2742fd	
2	QtAV::AVPlayer::Private::setupAudioThread	AVPlayerPrivate.cpp	285	0x7fffda274755	
3	QtAV::AVPlayer::playInternal	AVPlayer.cpp	995	0x7fffda26f77c	
4	QtAV::AVPlayer::qt_static_metacall	moc_AVPlayer.cpp	365	0x7fffda2a3262	
5	QMetaObject::activate(QObject*, int, int, void**)	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff6404e7a	
6	QtAV::AVPlayer::loaded	moc_AVPlayer.cpp	662	0x7fffda2a3e3f	
7	QtAV::AVPlayer::qt_static_metacall	moc_AVPlayer.cpp	321	0x7fffda2a2daa	
8	QObject::event(QEvent*)	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff6407326	
9	QCoreApplication::notify(QObject*, QEvent*)	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff63d2fdd	
10	QCoreApplication::notifyInternal(QObject*, QEvent*)	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff63d2c84	
11	QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff63d5868	
12	??	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff642d123	
13	g_main_context_dispatch	/lib/x86_64-linux-gnu/libglib-2.0.so.0		0x7ffff3c43c5d	
14	??	/lib/x86_64-linux-gnu/libglib-2.0.so.0		0x7ffff3c43f48	
15	g_main_context_iteration	/lib/x86_64-linux-gnu/libglib-2.0.so.0		0x7ffff3c43ffc	
16	QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff642d5b3	
17	QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff63d0eab	
18	QCoreApplication::exec()	/home/sakhter/Qt/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff63d5dc5	
19	main	main.cpp	132	0x4077fb	
...	<More>

**Comment by wang-bin** [comment] 2015-02-16 10:59
Can you build a debug executable and show more details in `initCommonStatistics`? I can't reproduce this crash.

**Comment by saqebakhter** [comment] 2015-02-16 16:59
There was not much more details but if I put a 1 second delay in if i put a
one second delay in "AVPlayer::Private::initAudioStatistics" - it seems to
fix the issue .... Not sure why though.

**Comment by wang-bin** [comment] 2015-02-17 03:53
How can I reproduce this crash?

**Comment by saqebakhter** [comment] 2015-02-17 04:51
I'm not entirely sure.. I'm running this in a VM using vmware, the vm is
xubuntu

**Comment by Ninissh** [comment] 2015-02-25 08:06
what sintax did you use to ad the 1 sec delay?

**Comment by wang-bin** [comment] 2015-06-24 14:14
should be fixed

**Closed by wang-bin** 2015-06-24 14:14 UTC
Labels: question
