### ISSUE TITLE
Video hangs if setAudioBackends is set to null

### ISSUE THREAD

**Issue by bongas** [wang-bin/QtAV#554] opened 2015-12-15 12:57 UTC
I am showing multiple AVPlayers on screen and only want one of them to output sound. Therefore I do this for all other AVPlayers:
`avPlayer->audio()->setBackends(QStringList() << "null");`

This seems to work (no audio) but when the video is ending the complete application hangs.
I have tried to use `avPlayer->audio()->setMute(true);` but it doesn't really work. The sound of the main player then becomes distorted. Also it seems that the videos run too fast.

Reproduce issue: `player -ao null`

Environment:
Latest QtAV
Ubuntu 14.04 and 15.10
Decoder: VAAPI, ffmpeg

Thanks
/Gabriel

**Comment by wang-bin** [comment] 2015-12-16 05:11
I can't reproduce it. Try the latest ppa, and `apt-get install libqtav libqtavwidgets qml-module-qtav qtav-players` and run `Player -ao null somevideo`

**Comment by bongas** [comment] 2015-12-16 14:21
It's the same behavior with the ppa version.
Here is the log: http://pastebin.com/eSCaEkXt
Here is my test video: https://drive.google.com/file/d/0BwTlBKoEwt-sTWpjYU5ua0JSS2c/view?usp=sharing

The last error message: `stopping thread  QtAV::AudioThread(0x1b04ab0)` is repeating once a second forever. The CPU goes to 100% and stays there.

**Comment by wang-bin** [comment] 2015-12-16 15:06
So strange. Your video plays fine for me. The log is strange too.
What about other videos? What about windows packages https://sourceforge.net/projects/qtav/files/ci/ ?

**Comment by bongas** [comment] 2015-12-17 08:43
Yeah, strange.
I now made a clean Ubuntu 15.10 installation and directly downloaded the ppa version and run the Player app. Same issue...
I have tested it on 3 different computers (with Ubuntu 14.04 and 15.10), all with the same issue.
I have also tested a lot of videos and it works well most of the times for mp4 files, but for all other file types I have tested the issue is there (mov, mkv, avi).

**Comment by bongas** [comment] 2015-12-17 09:17
Made som debugging and found out that, in the tear down phase, the AudioThread is just continuing to run even if stop is requested. This is due to that the infinite loop in run() always is coming to the `continue` call on row 156 in AudioThread.cpp. The `d.stop` is never checked and the loop is never ended...

**Comment by wang-bin** [comment] 2015-12-17 09:44
`d.stop` is checked somewhere else

**Comment by bongas** [comment] 2015-12-17 10:03
It seems that `d.stop` is not checked in the loop because the `pkt.isEOF()` is always true...

**Comment by wang-bin** [comment] 2015-12-17 15:01
`isEOF()` is true only if reading at the end of stream.
If more than 5 packets have no timestamp, then I assume the stream does not contains timestamps and play at 24fps. It's not the reason why playback is fine.

Did you tested on windows? I tested on ubuntu 15.10, win10 and OSX.

**Comment by bongas** [comment] 2015-12-18 12:20
I have no dev env on Window but I will try to set it up.

I checked out an old commit (e4bc2d4c5c5e699016ee53199b29d685cd15d6d0) of QtAV and with that version it works. The difference is that audio thread is not even started (because AudioOutputNull->open() is false) while in master commit the audio thread is running and is indefinitly looping.

**Comment by wang-bin** [comment] 2015-12-29 15:11
setAudioStream(-1) is a solution. I can't reproduce your issue so I close it.

**Closed by wang-bin** 2015-12-29 15:11 UTC
